from setuptools import setup

setup(
    name="OSM-Crosswalk-Detection",
    version="0.1.0",
    author="Buehler Severin and Kurath Samuel",
    maintainer="Marcel Huber",
    maintainer_email="marcel.huber@hsr.ch",
    description="Crosswalk detection on orthofotos.",
    license="MIT",
    keywords="crosswalk detection",
    url="https://github.com/geometalab/OSM-Crosswalk-Detection",
    packages=[
        'src',
        'src.base',
        'src.data',
        'src.detection',
        'src.detection.deep',
        'src.role'],
    install_requires=[
        'rq',
        'geopy',
        'pillow',
        'fake_useragent',
        'httplib2',
        'django-environ'],
    setup_requires=['flake8'],
    test_suite='tests',
    tests_require=['nose'],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Console",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Operating System :: POSIX :: Linux",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2.7",
        "Topic :: Scientific/Engineering :: GIS",
        "Topic :: Scientific/Engineering :: Image Recognition",
        "Topic :: Scientific/Engineering :: Visualization"],
)
