version: '3.8'
services:
  nbs: &nb
    build:
      context: ../
      dockerfile: docker/Dockerfile
      # when no gpu available:
      target: default
      # when cuda support is needed:
      # target: cuda
    user: "1000:1000"
    command: [
      "start-notebook.sh",
      "--ip=0.0.0.0",
      # "--allow-root",
      "--port=8088",
      "--NotebookApp.base_url=/",
      "--NotebookApp.token='7HDOWxPSk3hw0hB6hoWJ7l9YCvGgoqaNes4FLBvpaABrTJDTWE1AJPJjbt8zINfbLQ7m'",
      "--NotebookApp.password='7HDOWxPSk3hw0hB6hoWJ7l9YCvGgoqaNes4FLBvpaABrTJDTWE1AJPJjbt8zINfbLQ7m'",
    ]
    volumes:
      - ../:/home/jovyan/work/OSMDeepOD
    ports:
      - "8088:8088"
      # voila default port
      - "8866:8866"
      # image_app port
      - "8123:8123"
    shm_size: '10gb'

  # ONLY NEEDED WHEN DRAWING IMAGE BOXES
  # ims: &ims
  #   <<: *nb
  #   entrypoint: []
  #   command: >-
  #     bash -c '
  #     cd /home/jovyan/work/OSMDeepOD/src/
  #     && voila 002_BoxImagesTool.ipynb --port 8234 --no-browser --Voila.ip="0.0.0.0"'
  # 
  # im-service:
  #   <<: *ims
  #   command: >-
  #     bash -c '
  #     cd /home/jovyan/work/OSMDeepOD/src/
  #     && jupyter nbconvert --to notebook --execute 999_image_service.ipynb'
  #
  # proxy:
  #   image: njordan/env-configurable-caddy
  #   environment:
  #     # password: E2enzQKJ7I7UhSBcggUpGj17MHooY2kt6Qr
  #     # hash: JDJhJDE0JHRJY2FReGFGTGJwWU5uSjB2T0EzZXVWMUhGbUhlcHNTU1N5N250YVJYOUFDTWFLcmtBWU9l
  #     CADDY_CONFIG: |
  #       # {
  #       #   email njordan.hsr@gmail.com
  #       # }
  #       :8000 {
  #         basicauth / {
  #            segmentation-hero JDJhJDE0JHRJY2FReGFGTGJwWU5uSjB2T0EzZXVWMUhGbUhlcHNTU1N5N250YVJYOUFDTWFLcmtBWU9l
  #         }
  #         route {
  #           reverse_proxy /nbs* {
  #             to nbs:8088
  #           }
  #           reverse_proxy /* {
  #             to ims:8234
  #           }
  #         }
  #       }
  #   ports:
  #     - '8000:8000'
