version: '3.8'
services:
  nbs: &nb
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: default
      # when cuda support is needed:
      # target: cuda
    user: "1000:1000"
    command: [
      "start-notebook.sh",
      "--ip=0.0.0.0",
      # "--allow-root",
      "--port=8088",
      "--NotebookApp.base_url=/",
      "--NotebookApp.token='7HDOWxPSk3hw0hB6hoWJ7l9YCvGgoqaNes4FLBvpaABrTJDTWE1AJPJjbt8zINfbLQ7m'",
      "--NotebookApp.password='7HDOWxPSk3hw0hB6hoWJ7l9YCvGgoqaNes4FLBvpaABrTJDTWE1AJPJjbt8zINfbLQ7m'",
    ]
    volumes:
      - ../:/home/jovyan/work/OSMDeepOD
    ports:
      - "8088:8088"
      # voila default port
      - "8866:8866"
      # image_app port
      - "8123:8123"
    shm_size: '10gb'
  image-api:
    <<: *nb
    command: >-
      echo 0
    ports: []
